DROP TABLE [dbo].[PERSON];

CREATE TABLE [dbo].[PERSON] (
	[ID]			[INT] IDENTITY(1,1)	NOT NULL,
	[FIRST_NAME]	[NVARCHAR](225) 	NOT NULL,
	[LAST_NAME]		[NVARCHAR](225) 	NOT NULL,
	[MIN_DISTANCE]	[FLOAT] 			NOT NULL, 	--mm
	[MAX_DISTANCE]	[FLOAT] 			NOT NULL, 	--mm
 CONSTRAINT [PK_PERSON] PRIMARY KEY ([ID]),
 CONSTRAINT [UC_PERSON] UNIQUE ([FIRST_NAME], [LAST_NAME])
);

SET IDENTITY_INSERT [dbo].[PERSON] ON; 

DELETE FROM [dbo].[PERSON];

INSERT INTO [dbo].[PERSON] ([ID], [FIRST_NAME], [LAST_NAME], [MIN_DISTANCE], [MAX_DISTANCE]) VALUES (1, 'Michael', 'Tran', 0, 600);
INSERT INTO [dbo].[PERSON] ([ID], [FIRST_NAME], [LAST_NAME], [MIN_DISTANCE], [MAX_DISTANCE]) VALUES (2, 'Sue', 'Park', 0, 600);
INSERT INTO [dbo].[PERSON] ([ID], [FIRST_NAME], [LAST_NAME], [MIN_DISTANCE], [MAX_DISTANCE]) VALUES (3, 'Bambi', 'Tran', 0, 600);
INSERT INTO [dbo].[PERSON] ([ID], [FIRST_NAME], [LAST_NAME], [MIN_DISTANCE], [MAX_DISTANCE]) VALUES (4, 'Gloria', 'Tran', 0, 600);
INSERT INTO [dbo].[PERSON] ([ID], [FIRST_NAME], [LAST_NAME], [MIN_DISTANCE], [MAX_DISTANCE]) VALUES (5, 'Suspect', '54', 0, 600);

SET IDENTITY_INSERT [dbo].[PERSON] OFF;


CREATE PROCEDURE [dbo].[PR_ADD_PERSON]
	@FIRST_NAME nvarchar(50),
	@LAST_NAME nvarchar(50),
	@MIN_DISTANCE float,
	@MAX_DISTANCE float
AS
	IF NOT EXISTS(SELECT 1 FROM [dbo].[PERSON] WHERE [FIRST_NAME] = @FIRST_NAME AND [LAST_NAME] = @LAST_NAME)
	BEGIN;
		INSERT INTO [dbo].[PERSON] ([FIRST_NAME], [LAST_NAME], [MIN_DISTANCE], [MAX_DISTANCE]) VALUES (@FIRST_NAME, @LAST_NAME, @MIN_DISTANCE, @MAX_DISTANCE);
	END;
	ELSE
	BEGIN;
		UPDATE [dbo].[PERSON] SET [MIN_DISTANCE] = @MIN_DISTANCE, [MAX_DISTANCE] = @MAX_DISTANCE WHERE [FIRST_NAME] = @FIRST_NAME AND [LAST_NAME] = @LAST_NAME;
	END;
GO